#ifndef __ESP_INTERNAL_TIME_H
#define __ESP_INTERNAL_TIME_H

#define TIMER_GROUP_0_BASE_REG          0x3ff5F000
#define TIMER_GROUP_0_LACT_CONFIG       (TIMER_GROUP_0_BASE_REG + 0x0070)
#define TIMER_GROUP_0_LACT_LOW          (TIMER_GROUP_0_BASE_REG + 0x0078)
#define TIMER_GROUP_0_LACT_HIGH         (TIMER_GROUP_0_BASE_REG + 0x007C) 
#define TIMER_GROUP_0_LACT_UPDATE       (TIMER_GROUP_0_BASE_REG + 0x0080) 

#define TIMG_LACT_DIVIDER_V  0xFFFF
#define TIMG_LACT_DIVIDER_S  13

#endif